### ISSUE TITLE
Doubt 

### ISSUE THREAD

**Issue by ilynivin** [Ghalbeyou/react-legecy#1]
- is this project is open source ?

- if it was yes I will create a Contributors.md and code of conduct for your project as a pull request. 👍

**Comment by Ghalbeyou** [comment]
hello. yesss thanks!

**Comment by nivinvysakh** [comment]
#2

**Comment by Ghalbeyou** [comment]
hello. I did merge it. thanks for the help

**Comment by nivinvysakh** [comment]
Thanks mate !

**Comment by Ghalbeyou** [comment]
😅👍
